In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [2]:
# load the dataset
import pandas as pd

df = pd.read_csv(r"C:\Users\user\Desktop\AI automation\project_8\apple_products.csv")

In [3]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [4]:
df.isnull().sum()

Product Name           0
Product URL            0
Brand                  0
Sale Price             0
Mrp                    0
Discount Percentage    0
Number Of Ratings      0
Number Of Reviews      0
Upc                    0
Star Rating            0
Ram                    0
dtype: int64

# The Dataset doesnot has missing value

In [5]:
df.describe()

,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Star Rating
count,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000
mean,80073.887097,88058.064516,9.951613,22420.403226,1861.677419,4.575806
std,34310.446132,34728.825597,7.608079,33768.589550,2855.883830,0.059190
min,29999.000000,39900.000000,0.000000,542.000000,42.000000,4.500000
25%,49900.000000,54900.000000,6.000000,740.000000,64.000000,4.500000
50%,75900.000000,79900.000000,10.000000,2101.000000,180.000000,4.600000
75%,117100.000000,120950.000000,14.000000,43470.000000,3331.000000,4.600000
max,140900.000000,149900.000000,29.000000,95909.000000,8161.000000,4.700000

# Top 10 highest rated Iphone on Flipkart in India

In [6]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [8]:
highest_rated = df.sort_values(by= ["Star Rating"], ascending=False)
highest_rated = highest_rated.head(10)

In [9]:
print(highest_rated[["Product Name"]])

                                         Product Name
15              APPLE iPhone 11 Pro Max (Gold, 64 GB)
20    APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)
17        APPLE iPhone 11 Pro Max (Space Grey, 64 GB)
16   APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)
14             APPLE iPhone 11 Pro Max (Gold, 256 GB)
0                   APPLE iPhone 8 Plus (Gold, 64 GB)
12  Apple iPhone XR (Black, 128 GB) (Includes EarP...
11  Apple iPhone XR (Coral, 128 GB) (Includes EarP...
9   Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...
1            APPLE iPhone 8 Plus (Space Grey, 256 GB)

In [10]:
print(highest_rated)

                                         Product Name  \
15              APPLE iPhone 11 Pro Max (Gold, 64 GB)
20    APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)
17        APPLE iPhone 11 Pro Max (Space Grey, 64 GB)
16   APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)
14             APPLE iPhone 11 Pro Max (Gold, 256 GB)
0                   APPLE iPhone 8 Plus (Gold, 64 GB)
12  Apple iPhone XR (Black, 128 GB) (Includes EarP...
11  Apple iPhone XR (Coral, 128 GB) (Includes EarP...
9   Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...
1            APPLE iPhone 8 Plus (Space Grey, 256 GB)

                                          Product URL  Brand  Sale Price  \
15  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple      117100
20  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple      117100
17  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple      117100
16  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple      131900
14  https://www.flipkart.com/apple-iphone-11-pro-m...  Apple      131900
0   https://www.flipkart.com/apple-iphone-8-plus-g...  Apple       49900
12  https://www.flipkart.com/apple-iphone-xr-black...  Apple       41999
11  https://www.flipkart.com/apple-iphone-xr-coral...  Apple       41999
9   https://www.flipkart.com/apple-iphone-xr-produ...  Apple       41999
1   https://www.flipkart.com/apple-iphone-8-plus-s...  Apple       84900

       Mrp  Discount Percentage  Number Of Ratings  Number Of Reviews  \
15  117100                    0               1078                101
20  117100                    0               1078                101
17  117100                    0               1078                101
16  131900                    0               1078                101
14  131900                    0               1078                101
0    49900                    0               3431                356
12   52900                   20              79512               6796
11   52900                   20              79582               6804
9    52900                   20              79512               6796
1    84900                    0               3431                356

                 Upc  Star Rating   Ram
15  MOBFKCTSAPAYNSGG          4.7  4 GB
20  MOBFKCTSRYPAQNYT          4.7  4 GB
17  MOBFKCTSKDMKCGQS          4.7  4 GB
16  MOBFKCTSCAAKGQV7          4.7  4 GB
14  MOBFKCTS7HCHSPFH          4.7  4 GB
0   MOBEXRGV7EHHTGUH          4.6  2 GB
12  MOBF9Z7ZYWNFGZUC          4.6  3 GB
11  MOBF9Z7ZS6GF5UAP          4.6  4 GB
9   MOBF9Z7ZHQC23PWQ          4.6  4 GB
1   MOBEXRGVAC6TJT4F          4.6  2 GB

# how many rating do the highest- rated iPhones on Flipkart have

In [11]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [25]:
iphones = highest_rated['Product Name'].value_counts()
label = iphones.index
counts = highest_rated['Number Of Ratings']
figure = px.bar(highest_rated, x=label, y=counts )
figure.show()

# which iphone has the highest on flipkart

In [26]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [27]:
iphones = highest_rated['Product Name'].value_counts()
label = iphones.index
counts = highest_rated['Number Of Reviews']
figure = px.bar(highest_rated, x=label, y=counts, title = "Number of Reviews for the Highest Rated iPhones")
figure.show()

# What is the relationship between the sale price of iphone and the number of rating on Flipkart?

In [28]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [32]:
figure = px.scatter(
    data_frame=df,
    x="Number Of Ratings",
    y="Sale Price",
    size='Discount Percentage',
    color="Star Rating",
    trendline='ols',
    title='Relationship Between Number of Ratings and Sale Price'
)

figure.show()

- conclusion there is a negative relationship between the sale price of iphone and num of Rating

# relation discount percetage and the number of rating

In [33]:
figure = px.scatter(
    data_frame=df,
    x="Number Of Ratings",
    y="Discount Percentage",
    size='Sale Price',
    color="Star Rating",
    trendline='ols',
    title='Relationship Between Discount Percentage and Number of Ratings'
)

figure.show()

# most expensive and least expensive

In [34]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [35]:
most_expensive = df.loc[df['Sale Price'].idxmax()]
least_expensive = df.loc[df['Sale Price'].idxmin()]

print("Most Expensive iPhone:")
print(most_expensive)

print("\nLeast Expensive iPhone:")
print(least_expensive)

Most Expensive iPhone:
Product Name                        APPLE iPhone 12 Pro (Silver, 512 GB)
Product URL            https://www.flipkart.com/apple-iphone-12-pro-s...
Brand                                                              Apple
Sale Price                                                        140900
Mrp                                                               149900
Discount Percentage                                                    6
Number Of Ratings                                                    542
Number Of Reviews                                                     42
Upc                                                     MOBFWBYZ5UY6ZBVA
Star Rating                                                          4.5
Ram                                                                 4 GB
Name: 24, dtype: object

Least Expensive iPhone:
Product Name                              APPLE iPhone SE (White, 64 GB)
Product URL            https://www.flipkart.com/apple-iphone-se-white...
Brand                                                              Apple
Sale Price                                                         29999
Mrp                                                                39900
Discount Percentage                                                   24
Number Of Ratings                                                  95807
Number Of Reviews                                                   8154
Upc                                                     MOBFWQ6BGWDVGF3E
Star Rating                                                          4.5
Ram                                                                 2 GB
Name: 52, dtype: object